### ISSUE TITLE
Ecrire un petit setup.py pour pouvoir effectivement installer ça depuis 'pip install git+...'

### ISSUE THREAD

**Issue by Naereen** [Naereen/FreeSMS.py#2]
J'avais écrit [dans la documentation](https://github.com/Naereen/FreeSMS.py/#avec-pip-) que l'on peut faire

```bash
sudo pip install git+https://github.com/Naereen/FreeSMS.py
```

Mais ça ne marche pas ! Il n'y a pas de [`setup.py`](https://docs.python.org/3/distutils/setupscript.html) !

```bash
$ pip install git+https://github.com/Naereen/FreeSMS.py
Collecting git+https://github.com/Naereen/FreeSMS.py
  Cloning https://github.com/Naereen/FreeSMS.py to /tmp/pip-req-build-30ler4o9
  Running command git clone -q https://github.com/Naereen/FreeSMS.py /tmp/pip-req-build-30ler4o9
    ERROR: Command errored out with exit status 1:
     command: /tmp/rcviz/env3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-30ler4o9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-30ler4o9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1_z8sxf6
         cwd: /tmp/pip-req-build-30ler4o9/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-30ler4o9/setup.py'
    ----------------------------------------
WARNING: Discarding git+https://github.com/Naereen/FreeSMS.py. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Naereen** [comment]
Regarde ce fichier <https://github.com/Naereen/Jupyter-NBConvert-OCaml/blob/master/setup.py> ?
